basePath: /api/
definitions:
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.UserData:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: 172.27.227.76:8080
info:
  contact: {}
  description: API Server for TODO Application
  title: TODO App API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: user login to set auth cookie
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.UserData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Login
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: create account
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.UserData'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Register
      tags:
      - auth
swagger: "2.0"
